name: Release step

inputs:
  site:
    description: "The site to release"
    required: true

  cloudfont-id:
    description: "The Cloudfront ID to invalidate"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials from PRODUCTION account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-role
        aws-region: ${{ secrets.AWS_PROD_REGION }}

    - name: Release-docs 
      uses: dagger/dagger-for-github@v5
      with:
        version: "0.11.8"
        verb: call
        module: github.com/${{ github.repository }}@${{ github.ref }}
        args: |
          --ref ${{ github.ref }} \
          release \
          --site="${{ inputs.site }}" \
          --aws-region=$AWS_REGION \
          --aws-access-key-id=env:AWS_ACCESS_KEY_ID \
          --aws-secret-access-key=env:AWS_SECRET_ACCESS_KEY \
          --aws-session-token=env:AWS_SESSION_TOKEN \
          --cloudfront-id=${{ inputs.cloudfont-id }} \
      env:
          AWS_REGION: ${{ secrets.AWS_PROD_REGION }}
