name: Deploy to Production 🚀

on:
  push:
    branches:
      - 'main'
  # Enable manual trigger for easier debugging
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "Docs publish"
        uses: ./.github/actions/call
        with:
          site: "docs"
          cloudfont-id: ${{ secrets.DOCS_CLOUDFRONT_ID }}

  widget:
    runs-on: ubuntu-latest
    steps:
      - name: "Widget publish"
        uses: ./.github/actions/call
        with:
          site: "widget"
          cloudfont-id: ${{ secrets.WIDGET_CLOUDFRONT_ID }}
